export const GET_JOBS_LOADING = "GET_JOBS_LOADING";
export const GET_JOBS_ERRORS = "GET_JOBS_ERRORS";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

//change status
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_ERRORS = "CHANGE_STATUS_ERRORS";
export const CHANGE_STATUS_LOADING = "CHANGE_STATUS_LOADING";
